In [45]:
import numpy as np
from scipy import linalg



In [46]:
## 9.1 Matrix Operations 

# create matrix A with random Gaussian entries 

n = 200 
m = 500

p = (n,m)
A = np.random.normal(size=p)
A
print(A.ndim)
print(A.shape)
print(len(A))

2
(200, 500)
200


In [47]:
# create matrix B as a Toeplitz matrix

h = np.arange(1, 500)

padding = np.zeros(h.shape[0], h.dtype)
first_col = np.r_[h, padding]
first_row = np.r_[h[0], padding]

B = linalg.toeplitz(first_col, first_row)

print(repr(B))

array([[  1,   0,   0, ...,   0,   0,   0],
       [  2,   1,   0, ...,   0,   0,   0],
       [  3,   2,   1, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ..., 499, 498, 497],
       [  0,   0,   0, ...,   0, 499, 498],
       [  0,   0,   0, ...,   0,   0, 499]])


In [48]:
print(A)

[[ 0.58792839 -0.05070725 -1.07192871 ... -2.32317697 -0.66942904
  -1.27996755]
 [-0.12631249  0.4002551  -2.59303965 ... -0.17371784 -0.13896636
   0.78017213]
 [ 0.3774355  -1.60032584  0.05930846 ... -1.34495976 -1.08812244
   1.08908562]
 ...
 [-0.81343562 -0.55312257  0.48641669 ...  1.07525149  1.28497187
   0.84408968]
 [-1.02476595  0.29702607 -0.36192834 ... -0.64072686  0.6510871
   1.5080086 ]
 [-0.29263093  0.72602889 -1.10211073 ... -0.81866191  0.79455536
   0.51242459]]


In [49]:
# Matrix addition: A+A

Asum = A + A

In [50]:
Asum

array([[ 1.17585678, -0.10141451, -2.14385742, ..., -4.64635393,
        -1.33885808, -2.55993509],
       [-0.25262498,  0.80051021, -5.1860793 , ..., -0.34743569,
        -0.27793273,  1.56034426],
       [ 0.75487101, -3.20065168,  0.11861692, ..., -2.68991952,
        -2.17624489,  2.17817123],
       ...,
       [-1.62687123, -1.10624514,  0.97283338, ...,  2.15050298,
         2.56994375,  1.68817935],
       [-2.0495319 ,  0.59405213, -0.72385667, ..., -1.28145371,
         1.30217421,  3.0160172 ],
       [-0.58526186,  1.45205779, -2.20422145, ..., -1.63732383,
         1.58911072,  1.02484917]])

In [51]:
# Matrix multiplication: A*AT (transpose)

Aprod = np.dot(A,A.T)

In [52]:
Aprod

array([[444.33912934, -10.35167158,  47.24226458, ..., -16.97164192,
        -27.00002907, -31.21025388],
       [-10.35167158, 499.06427775, -12.06802733, ..., -23.66225818,
        -39.97624503,  17.62372481],
       [ 47.24226458, -12.06802733, 433.08881157, ...,  41.71021501,
         -8.50952414, -20.68705261],
       ...,
       [-16.97164192, -23.66225818,  41.71021501, ..., 510.03944578,
          6.18400317, -13.06843401],
       [-27.00002907, -39.97624503,  -8.50952414, ...,   6.18400317,
        455.07123884,  -7.65568997],
       [-31.21025388,  17.62372481, -20.68705261, ..., -13.06843401,
         -7.65568997, 484.53749864]])

In [53]:
# Matrix multiplication: AT*A 

Aprod = np.dot(A,A.T)
Aprod2 = np.dot(A.T,A)

In [54]:
Aprod2

array([[ 1.54615542e+02, -1.94630636e+01,  3.19760942e+00, ...,
        -9.72647103e+00, -1.86304040e+01, -1.34811755e+01],
       [-1.94630636e+01,  1.98229102e+02, -2.34714748e+01, ...,
        -1.75677050e-01,  1.78609440e+01, -1.64852730e+01],
       [ 3.19760942e+00, -2.34714748e+01,  1.68386818e+02, ...,
        -1.42020942e+00, -2.03226618e+00,  8.06154133e+00],
       ...,
       [-9.72647103e+00, -1.75677050e-01, -1.42020942e+00, ...,
         1.55176516e+02,  9.27855451e+00,  1.04484759e+01],
       [-1.86304040e+01,  1.78609440e+01, -2.03226618e+00, ...,
         9.27855451e+00,  1.91399542e+02, -6.30576819e+00],
       [-1.34811755e+01, -1.64852730e+01,  8.06154133e+00, ...,
         1.04484759e+01, -6.30576819e+00,  2.11584792e+02]])

In [55]:
# Matrix multiplication: A*B

Aprod = np.dot(A,A.T)
AB = np.dot(A,B)
AB

ValueError: shapes (200,500) and (998,500) not aligned: 500 (dim 1) != 998 (dim 0)

In [56]:
# 9.2 Solving a linear system

In [85]:
b = np.random.random_sample(m)

In [86]:
b

array([0.46915931, 0.00790816, 0.79050095, 0.97477425, 0.44525143,
       0.21807331, 0.03994015, 0.48948098, 0.84917278, 0.51956005,
       0.06120432, 0.84959595, 0.48727329, 0.21976556, 0.91385057,
       0.0790767 , 0.3329952 , 0.34044959, 0.06734441, 0.96097086,
       0.58243094, 0.5728365 , 0.50005826, 0.82546705, 0.40802637,
       0.74678112, 0.09300535, 0.79170583, 0.10032604, 0.05117363,
       0.80964122, 0.41019614, 0.909937  , 0.01653032, 0.01339812,
       0.16593442, 0.45988392, 0.22710758, 0.83853619, 0.92973376,
       0.18523941, 0.84409994, 0.25937702, 0.4138678 , 0.94029803,
       0.61938618, 0.1114028 , 0.33659235, 0.95440122, 0.36600785,
       0.30281744, 0.7081597 , 0.7633415 , 0.81664798, 0.28378799,
       0.93828698, 0.73036809, 0.21330742, 0.5416829 , 0.64582664,
       0.15191021, 0.52558552, 0.56476593, 0.46764316, 0.19323013,
       0.94282817, 0.7646161 , 0.61411623, 0.40515171, 0.44388094,
       0.24190366, 0.64927641, 0.72987952, 0.95123892, 0.11088

In [89]:
# Solving Bx = b for x

x = b / B[:,None]
x

/Users/Charu/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([[[4.69159305e-01,            inf,            inf, ...,
                    inf,            inf,            inf]],

       [[2.34579653e-01, 7.90815892e-03,            inf, ...,
                    inf,            inf,            inf]],

       [[1.56386435e-01, 3.95407946e-03, 7.90500952e-01, ...,
                    inf,            inf,            inf]],

       ...,

       [[           inf,            inf,            inf, ...,
         1.75571938e-03, 1.10937940e-03, 1.66709704e-04]],

       [[           inf,            inf,            inf, ...,
                    inf, 1.10715620e-03, 1.66374945e-04]],

       [[           inf,            inf,            inf, ...,
                    inf,            inf, 1.66041529e-04]]])

In [17]:
y = (B.T / b).T
y

ValueError: operands could not be broadcast together with shapes (500,998) (500,) 

In [18]:
# 9.3 Norms

AF = np.linalg.norm(A)
print("Frobenius norm of A:", AF)

Frobenius norm of A: 316.10987923317543


In [19]:
BI = np.linalg.norm(B, np.inf)
print("Infinity norm of B:", BI)

Infinity norm of B: 124750.0


In [20]:
# largest and smallest values of B

Bmax = np.amax(B)
print("Max:",Bmax)

Bmin = np.amin(B)
print("Min:", Bmin)

Max: 499
Min: 0


In [21]:
# 9.4 Power iteration 

In [27]:
# Generate matrix Z (n x n) with Gaussian entries

n2 = (n,n)
Z = np.random.normal(size =n2)
Z


array([[-0.93211405,  0.63658849,  1.90314761, ..., -0.17975024,
        -0.8849216 , -0.41522488],
       [ 0.47418003, -0.04194635, -0.9906285 , ...,  0.15016387,
         0.97619527, -0.42657454],
       [-1.83778604,  0.9163409 , -0.61090997, ...,  0.60526514,
         0.31617092,  1.98562179],
       ...,
       [-0.93413854,  0.02317627, -0.57654328, ..., -2.02621204,
         0.03423272,  1.39462632],
       [ 1.33596511, -1.33277932,  1.5556325 , ..., -0.67353746,
        -0.07236887, -0.23283183],
       [ 1.04129662, -0.43429118,  1.04496333, ...,  0.31637084,
        -0.68825856,  1.9248547 ]])

In [28]:
print(Z.shape)

(200, 200)


In [42]:
# Finding largest eigenvalue and eigenvector 

def eigenvalue(Z, v):
    Zv = Z.dot(v)
    return v.dot(Zv)

def power_iteration(Z):
    n, d = Z.shape

    v = np.ones(d) / np.sqrt(d)
    ev = eigenvalue(Z, v)

    while True:
        Zv = Z.dot(v)
        v_new = Zv / np.linalg.norm(Zv)

        ev_new = eigenvalue(Z, v_new)
        if np.abs(ev - ev_new) < 0.01:
            break

        v = v_new
        ev = ev_new
    
    print("Largest eigenvalue =", ev_new)
    print("Eigenvector =", v_new)
    


In [44]:
power_iteration(Z)


Largest eigenvalue = -0.05154683374083968
Eigenvector = [-0.01530291 -0.0077359  -0.02580054  0.06896933  0.05164872  0.07720097
 -0.07955511  0.00481715 -0.03830329  0.02241969  0.09647641 -0.01220312
 -0.03823739  0.18021661  0.00959739  0.11081783 -0.03980164 -0.11165426
 -0.05634568  0.04491649 -0.01099544 -0.07033972  0.02109181  0.04761199
 -0.0397024  -0.01046379  0.10609561 -0.07306316 -0.03945914 -0.06605715
 -0.03584329 -0.0945471  -0.02424921 -0.15004133  0.00345266  0.02644114
  0.06313387  0.02483728 -0.10725933 -0.08611772 -0.00329595  0.00378318
  0.03832197  0.01333318 -0.02407487  0.04794961  0.00532754  0.09068559
  0.01642151 -0.03194056 -0.05082474 -0.02062507 -0.03100887  0.10875611
 -0.00584463 -0.0065085  -0.08585047  0.13523574 -0.06839697  0.00257374
 -0.09877528  0.02327825 -0.0117145   0.02855841  0.0092079   0.04502331
 -0.0905687  -0.03001552 -0.16443287  0.06998867  0.01093156 -0.01746009
 -0.04501603 -0.02258894  0.02773169  0.08461851 -0.10306386  0.0912